# Generated by Django 6.0.3 on 2026-04-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='available_equipment',
            field=models.CharField(blank=True, choices=[('full_gym', 'Full Gym'), ('home_gym', 'Home Gym'), ('none', 'No Equipment')], max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_steps',
            field=models.CharField(blank=True, choices=[('under_4k', '<4,000'), ('4k_7k', '4,000–7,000'), ('7k_10k', '7,000–10,000'), ('10k_13k', '10,000–13,000'), ('over_13k', '13,000+')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('pro', 'Pro')], max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('build_muscle', 'Build Muscle / Maintain'), ('bulk_and_cut', 'Bulk & Cut'), ('stay_fit', 'Stay Fit')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hours_sitting',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hours_standing',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_type',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary / Office'), ('lightly_active', 'Lightly Active / Standing'), ('active', 'Active / Manual Labor'), ('heavy', 'Heavy Manual Labor')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_food_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sleep_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sport_types',
            field=models.CharField(blank=True, help_text='Comma-separated: Ball Sports, Gym/Strength, Calisthenics, Endurance, Martial Arts', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='training_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes per session', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='training_frequency',
            field=models.PositiveIntegerField(blank=True, help_text='Days per week', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
