# Generated by Django 6.0.3 on 2026-04-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age_user_available_equipment_user_daily_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='body_fat_category',
            field=models.CharField(choices=[('lean', 'Lean (~10-15%)'), ('athletic', 'Athletic (~16-22%)'), ('average', 'Average (~23-29%)'), ('above_average', 'Above Average (~30%+)')], default='', max_length=15),
        ),
    ]
