# Generated by Django 6.0.3 on 2026-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_body_fat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='body_fat_category',
            field=models.CharField(choices=[('m10', '~10% body fat'), ('m15', '~15% body fat'), ('m20', '~20% body fat'), ('m25', '~25% body fat'), ('m30', '~30% body fat'), ('f15', '~15% body fat'), ('f20', '~20% body fat'), ('f25', '~25% body fat'), ('f30', '~30% body fat'), ('f35', '~35% body fat')], default='', max_length=15),
        ),
    ]
